### PR TITLE
Updated Velocity core library version to 2.0

### PR DESCRIPTION
**Pull request by dmaidaniuk**

### CODE REVIEW

**Comment by Daniel-Dos** [comment]
Quite Cool @dmaidaniuk , you managed to make it work without relying on Velocity Tools.

**Comment by dmaidaniuk** [comment]
Hi @Daniel-Dos ,

Yeah, I just followed by suggestion from @chkal and moved class `WebappResourceLoader` directly into extension project. :)

**Comment by Daniel-Dos** [comment]
Very Good @dmaidaniuk  .

Thanks. : )

**Comment by chkal** [comment]
This looks great! And all the tests passed! Great work.

However, I think we should switch to the Velocity Tools dependency after the new version has been released so that we get future updates of this class.

I'll merge this now. Thanks.

**Comment by dmaidaniuk** [comment]
Hi @chkal ,

Definitely we need to switch back to `velocity-tools-view` when its version 3.0 will be released.

Regards,
Dmytro

**Pull request merged**
