### PR TITLE
Register Ozark beans with CDI extension mechanism

### PR DESCRIPTION
**Pull request by rahmanusta**
This is the first part of my work "Register Ozark beans with CDI extension mechanism"

### CODE REVIEW

**Comment by rahmanusta** [comment]
I wonder why it is failed :) @chkal @lefloh

**Comment by rahmanusta** [comment]
It is failed because we should update the ViewEngineFinder, so you can merge it, it will be fixed in upcoming PR

**Comment by rahmanusta** [comment]
Interestingly injected BeanManager doesn't find registered beans, but CDI.current does that. @chkal @lefloh May it be a CDI bug ?

**Comment by chkal** [comment]
Hey @rahmanusta. Feel free to include the ViewEngineFinder modification required in this PR. Let's try to keep the tests green.

But actually it is very weird that `@Inject BeanManager` doesn't work but `CDI.current().getBeanManager` does. Actually this should resolve to the same BeanManager.

**Comment by chkal** [comment]
I can confirm for some reasons there are two bean managers:

Calling `toString()` on the result of `@Inject BeanManager` returns:

    Weld BeanManager for org.glassfish.ozark.cdi.OzarkCdiExtension [bean count=57]

And doing the same for `CDI.current.getBeanManager()` returns:

    Weld BeanManager for root_test-freemarker [bean count=28]

Now that's confusing.... :confused:

**Comment by rahmanusta** [comment]
@chkal This is the answer, at least we know there can be more different BeanManager for each module. I found this http://stackoverflow.com/questions/22807435/understanding-cdi-weld-in-multi-module-application

**Comment by chkal** [comment]
Thanks, I'll have a depper look at the second link which looks promising...

My findings so far. Before applying your patch we have this:

```
@Inject BeanManager:
    Weld BeanManager for WEB-INF/lib/ozark-1.0.0-m03-SNAPSHOT [bean count=67]]]
CDI.current().getBeanManager():
    Weld BeanManager for WEB-INF/lib/ozark-1.0.0-m03-SNAPSHOT [bean count=67]]]
```

After applying it we have:

```
@Inject BeanManager:
    Weld BeanManager for org.glassfish.ozark.cdi.OzarkCdiExtension [bean count=57]]]
CDI.current().getBeanManager():
    Weld BeanManager for root_test-freemarker [bean count=28]]]
JNDI lookup:
    Weld BeanManager for test-freemarker [bean count=30]]]
```

**Comment by rahmanusta** [comment]
Very interesting, how we will go forward? Do you still have this opinion "**Feel free to include the ViewEngineFinder modification required in this PR. Let's try to keep the tests green.**"

**Comment by chkal** [comment]
I'll try to contact Martin Kouba regarding this and see what he thinks. I guess the Weld project lead can help us here.

I think doing the ViewEngineFinder modification you did in the other PR will work, but it would be great to get some clarification about the situation because we are using `@Inject BeanManager` also at other places...

**Comment by rahmanusta** [comment]
Let's try to join them this conversation,

Hi @antoinesd, @mkouba , we have an issue about accessing BeanManager. When we apply a CDI extension to Ozark project, we are getting 3 different BeanManager that Christian described it above. It is very complicated for us, How should we move ?

Thanks.

**Comment by rahmanusta** [comment]
> BTW: Only @Inject BeanManager (after applying your patch) doesn't find the additional view engines.

Yes, `CDI.current().getBeanManager()` and `JNDI lookup for java:comp/BeanManager:` work for us,  but we should clarify this issue.

**Comment by mkouba** [comment]
Hi guys, in Weld there is not just a single `BeanManager`. Instead we have a `BeanManager` per bean archive. 

I'm not really sure what the original motivation was but I suppose it's mainly because some BM methods require some context - e.g. `getBeans()` _"Returns the set of beans which have the given required type and qualifiers and **are available for injection in the module or library** containing the class into which the BeanManager was injected..."_. 

Note that the spec does not say anything like "there is a single BeanManager per application".

**Comment by rahmanusta** [comment]
Thank you @mkouba, it is strange to me but it is good to clarify current state of BeanManager from our side.

@chkal I echoed bean instances in a sheet to compare our situation clearly. Please look at that. https://docs.google.com/spreadsheets/d/1LHjq7Ph9rJlW3N7AFMQVOVy0nBIEAVwrXuBDz6rnr4k/edit?usp=sharing

**Comment by chkal** [comment]
Hey @mkouba,

let me try to explain what we are doing here. Currently Ozark is a standard CDI archive with a `beans.xml` file. We have a test web application which basically looks like this:


```
test-freemarker.war
├── ...
└── WEB-INF
    ├── beans.xml
    ├── classes
    │   └── ...
    └── lib
        ├── ....
        ├── ozark-1.0.0-m03-SNAPSHOT.jar
        └── ozark-freemarker-1.0.0-m03-SNAPSHOT.jar
```

Now if we try to obtain the bean manager via different methods we are getting this result:

```
@Inject BeanManager into Ozark class:
    Weld BeanManager for WEB-INF/lib/ozark-1.0.0-m03-SNAPSHOT [bean count=67]]]

CDI.current().getBeanManager() from an Ozark bean:
    Weld BeanManager for WEB-INF/lib/ozark-1.0.0-m03-SNAPSHOT [bean count=67]]]

JNDI lookup for java:comp/BeanManager:
    Weld BeanManager for test-freemarker [bean count=30]]]
```

This basically looks fine to me. Ozark gets its BM and the web application BM is visible via JNDI. Everything fine so far.

Now we are in the process of preparing Ozark do be deployable as a Glassfish module. According to our knowledge this means that we cannot use `beans.xml` in the main Ozark JAR any more. So this pull request removes `beans.xml` from the main Ozark JAR and adds some code to `OzarkCdiExtension` which observers `BeforeBeanDiscovery` to register all annotated types required by Ozark.

Now we are getting this when deploying the same application (with Ozark still being in `/WEB-INF/lib`):

```
@Inject BeanManager into Ozark class:
    Weld BeanManager for org.glassfish.ozark.cdi.OzarkCdiExtension [bean count=57]]]

CDI.current().getBeanManager() from an Ozark bean:
    Weld BeanManager for root_test-freemarker [bean count=28]]]

JNDI lookup for java:comp/BeanManager:
    Weld BeanManager for test-freemarker [bean count=30]]]
```

This looks a bit surprising to us. But the main problem is that the BM obtained with the first method (injecting via `@Inject`) doesn't seem to have access to all the beans in other archives. In our case we have an interface `ViewEngine` and there are multiple implementations in different locations.

* Main Ozark JAR
  * `JspViewEngine`
  * `FaceletsViewEngine`
* Ozark Freemarker JAR
  * `FreemarkerViewEngine`

So if we use the injected BeanManager from within Ozark, we don't get the `FreemarkerViewEngine`. In all other cases we get all the view engines. That's a bit confusing. ;)

**Comment by mkouba** [comment]
What does it actually mean "deployable as a Glassfish module"? If the goal is to make it a part of Glassfish then you should not include Ozark jar in the deployment...

**Comment by chkal** [comment]
Actually we want to be able to do both. ;)

1. Install Ozark as a Glassfish module so that Ozark is provided by the container. The WAR file doesn't have to include Ozark in this case any more.
2. For other containers like Tomcat it should be possible to include Ozark in `/WEB-INF/lib`.

Our goal was to build Ozark in way that allows both usage scenarios.

**Comment by mkouba** [comment]
I see. So the second result is Ozark (with extended OzarkCdiExtension) deployed to Tomcat + Weld Servlet? If so, the BM obtained with the first method should see all the beans. However, note that alternatives, interceptors and decorators enabled/selected for a bean archive (not by means of `@Priority`) might be problematic.

**Comment by chkal** [comment]
No, not exactly. Both examples are deployed to latest Glassfish nightly with Weld being provided by Glassfish. The WAR archive contains just Ozark in `/WEB-INF/lib/`.

The only difference between the two examples:

  * Example 1:
    * Ozark JAR contains `beans.xml` with bean-discovery-mode="all"
  * Example 2:
    * Ozark JAR contain **no** `beans.xml` and all relevant CDI beans are registered via an extension.

**Comment by mkouba** [comment]
Ok. The only problematic part I can see is that GlassFish must create a kind of additional/synthetic bean archive for Ozark/OzarkCdiExtension. And this bean archive should follow the Java EE class accessibility requirements. So in this case Ozark should see/be visible from all the bean archives from the webapp.

Also note that this is not clearly defined by the spec, see also https://issues.jboss.org/browse/CDI-233.

**Comment by chkal** [comment]
@mkouba Thanks a lot for sharing your thoughts on this. So do you think this is more a Glassfish than a Weld issue?

**Comment by smillidge** [comment]
@Pandrex247 (in the Payara team) is approaching this by building a separate Payara module to do the bean registration.

**Comment by rahmanusta** [comment]
@smillidge Is there anything different between a GF module and a Payara module ?

**Comment by arjantijms** [comment]
It looks like the three different ways to obtain beans are via:

1. ``@Inject``
1. ``CDI.current().select()`` / ``CDI.current().getBeanManager()``
1. ``initialContext.lookup("java:comp/BeanManager")``

Then there are two locations to put spec implementation jars (e.g. Ozark, Soteria, Mojarra):

1. WEB-INF/lib
1. Inside the server (e.g. /modules in Payara)

And then we have many different servers:

1. Payara
1. JBoss
1. TomEE
1. Liberty
1. etc

From initial testing I found quite a number of those combinations behave differently.

E.g. in Payara ``@Inject`` doesn't work in a container jar, but ``CDI.current()`` and ``initialContext.lookup("java:comp/BeanManager")`` do.

However, in JBoss ``CDI.current()`` does not work in a container jar, but ``initialContext.lookup("java:comp/BeanManager")`` does.

I'll soon try if I can put together a kind of matrix to make it clear what the exact differences are.

**Comment by rahmanusta** [comment]
Thank you @arjantijms for explaining your experience in similar issue. If the JNDI lookup method works for all platforms, we can use it with a simple helper method in our CdiUtils class. What is your opinion @chkal ?

**Comment by rahmanusta** [comment]
My last PR is here https://github.com/mvc-spec/ozark/pull/12, at the end it seems me not too complex and I made it in a single PR.

**Comment by chkal** [comment]
@arjantijms Thanks a lot for sharing your experiences. Some kind of matrix would be really helpful. And I also think that we may need to move the discussion to cdi-dev!?!

**Pull request closed without merging**
