### PR TITLE
Pebble integration

### PR DESCRIPTION
**Pull request by vsmid**
Empty property values stated in properties file or via system properties will now be ignored.

### CODE REVIEW

**Comment by chkal** [comment]
Thanks! Looks good to me.

**Comment by chkal** [comment]
One additional note:

For some reason the Travis build started to fail for my own fork after your PR has been merged. Looks like your tests are failing. Any idea?

See:
https://travis-ci.org/chkal/ozark/builds/257603353

Not sure why this is happening. It looks like the build always works when Travis builds `mvc-spec/ozark` but it always fails for `chkal/ozark`. Although both repos are in sync.

**Comment by vsmid** [comment]
Hi, 

currently i am at work so i will take a look at it when i get home. I will let you know if i found anything.

**Comment by chkal** [comment]
Great! No need to hurry. Actually the build is running fine on the official repo, but I wonder what is causing this issue on my clone.

**Comment by vsmid** [comment]
Hi, 

i cloned your fork and executed tests locally. Tests were executed with no error.
After that i compared our forks and the only notable diff that i could find which could be connected to Travis failing build was this:

your .travis.yml

language: java
jdk: oraclejdk8
env:
  - TYPE=glassfish-module
  - TYPE=glassfish-bundled
install:
  - curl -s -o glassfish5.zip http://download.oracle.com/glassfish/5.0/nightly/glassfish-5.0-web-b10-06_29_2017.zip
  - unzip -q glassfish5.zip
script:
  - ./.travis-build.sh ${TYPE}
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)


my .travis.yml:

language: java
jdk: oraclejdk8
env:
  - TYPE=glassfish-module
  - TYPE=glassfish-bundled
install:
  - mvn dependency:get -Dartifact=javax.mvc:javax.mvc-api:1.0-SNAPSHOT -DremoteRepositories=central::default::https://repo1.maven.org/maven2,javanet::default::https://maven.java.net/content/repositories/snapshots
  - curl -s -o glassfish5.zip http://download.oracle.com/glassfish/5.0/promoted/latest-web.zip
  - unzip -q glassfish5.zip
script:
  - ./.travis-build.sh ${TYPE}
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

**Comment by chkal** [comment]
Thanks for having a look at this issue. I removed the `mvn dependency:get` line about two weeks ago and also updated the Glassfish version to run the integration tests against. That shouldn't cause any issues. You should fetch the latest updates from `mvc-spec/ozark` to sync your fork.

Could this be an issue with tests depending on being executed in a specific order? Perhaps Travis uses some older Maven version with an older Surefire plugin which runs tests in a different order? Just guessing here. But as I wrote earlier: It looks like `mvc-spec/ozark` and `chkal/ozark` seems to behave differently even for the exact same Git revision.

We could try to run the test with this to check for ordering issues:

    mvn clean install -Dsurefire.runOrder=random

I could try to do so tomorrow if I find some time.

**Comment by chkal** [comment]
BTW: I just checked the logs. Looks like the failed Travis executed them in a different order:

[Good Build](https://travis-ci.org/mvc-spec/ozark/jobs/257636041):

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.107 sec
Running org.glassfish.ozark.test.pebble.PebbleViewEngineTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running org.glassfish.ozark.test.pebble.PebbleEngineProducerTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.209 sec
Running org.glassfish.ozark.test.pebble.PebblePropertyTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Tests run: 21, Failures: 0, Errors: 0, Skipped: 0
```

[Failed Build](https://travis-ci.org/chkal/ozark/jobs/257632229):

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.glassfish.ozark.test.pebble.PebbleEngineProducerTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.316 sec
Running org.glassfish.ozark.test.pebble.PebblePropertyTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest
Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE!
systemPropertyShouldHaveHigherPriorityThanTheOneFromPropertyFile(org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest.systemPropertyShouldHaveHigherPriorityThanTheOneFromPropertyFile(PebbleConfigurationProducerTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

shouldReturnPebbleConfiguration(org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest.shouldReturnPebbleConfiguration(PebbleConfigurationProducerTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.glassfish.ozark.test.pebble.PebbleViewEngineTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec

Results :

Failed tests:   systemPropertyShouldHaveHigherPriorityThanTheOneFromPropertyFile(org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest)
  shouldReturnPebbleConfiguration(org.glassfish.ozark.test.pebble.PebbleConfigurationProducerTest)

Tests run: 20, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by vsmid** [comment]
Hi, 

test ordering should not matter in this case i think, this class does not contain dependant tests, hmmm.
I will sync my fork to see if it works.

**Comment by vsmid** [comment]
Hi, 

my fork is actually synced with master by the looks of it :-)

**Comment by vsmid** [comment]
Hi, 

i synced my fork master and performed Travis build. Everything went fine.

https://travis-ci.org/vsmid/ozark <https://travis-ci.org/vsmid/ozark>

**Comment by chkal** [comment]
Good news. I was able to fix this issue. For some reason tests are sometime executed in a different order. The problem was that `PebblePropertyTest` sets a system property to configure the engine and `PebbleConfigurationProducerTest` asserts the number of configuration entries. So if `PebblePropertyTest` runs before `PebbleConfigurationProducerTest`, these assertions will fail. I removed the size assertions as they aren't actually helpful for testing the desired behavior. See https://github.com/mvc-spec/ozark/commit/027b413e385863bc3b070c1dddd3a16b8ed015c8 for details.

**Comment by vsmid** [comment]
Hi, 

great, i am glad it works now, thanks! :-)

**Pull request merged**
